# -*- coding: utf-8 -*-
"""Input-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAoWBwFxfzjk7-IfYMkhmWw7rvOf5-Fl

1
"""

num1 = int(input('digite um número inteiro '))
num2 = int(input('digite outro número que deseja somar ao primeiro '))
total = num1 + num2

print('o resultado de', num1, "mais", num2, 'é', total)

"""2

"""

metros = float(input("digite um valor em metros "))
mm = metros * 1000

print("o valor", metros, "metros tem", mm, "milimetros")

"""3"""

dias = int(input('digite a quantidade de dias: ' ))
horas = int(input('digite a quantidade de horas: '))
minutos = int(input('digite a quantidade de minutos: ' ))

segundos = dias *86400, horas *3600, minutos *60

print("o valor em segundos será", segundos)

"""4"""

salario = float(input('digite o salário: '))
porcentagem = float(input('digite a porcentagem de aumento: '))

aumsal = salario * porcentagem /100
novo_salario = aumsal + salario
aumento = novo_salario - salario

print('o novo salário será', novo_salario, 'e o aumento foi de', aumento, 'reais')

"""5

"""

valorm = float(input('digite o valor da mercadoria: '))
porcentagem1 = float(input('digite o percentual de desconto: '))

porcentagem2 = (porcentagem1 /100) * valorm
valormnovo= valorm - porcentagem2

print(f'o valor do desconto será {porcentagem2: .2f} reais, e o novo valor será de {valormnovo: .2f} reais')

"""6"""

distancia = float(input('digite a distância percorrida em km: '))
velocidade = int(input('digite a velocidade em km/h: '))

tempo = distancia / velocidade

print('a viagem durou', tempo, "horas")

"""7"""

C = float(input("digite a temperatura em celsius "))
F = 9/5 * C + 32

print(f'temperatura {C:.2f} celsius = {F:.2f} Fahreinheit')

"""8"""

km = float(input('digite a distância percorrida pelo cliente: '))
dias = int(input('digite a quantidade de dias pelos quais o carro foi alugado: '))
preco1 = km * 60
preco2 = dias * 0.15
preco3 = preco1 + preco2

print('o preço a ser pago será de', preco3, 'reais')

"""9

"""

cigarro = int(input('quantos cigarros você fuma por dia? '))
tempo = int(input('por quantos anos você fumou? '))

minpordia = cigarro * 10
tempoperdido = round(minpordia * 365 * tempo / 1440)


print("você perdeu", tempoperdido, "dias")

"""10"""

import sys
sys.set_int_max_str_digits(0)

numerozao = 2**1000000

print('dois elevado a um milhão tem', len(str(numerozao)), 'digitos')