# -*- coding: utf-8 -*-
"""while-for-def

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UygWoZ5M1r1QCrYU1t6Fu2JFmP1tXegi

1)
"""

num=0
somanum=0
quantnum=0
quantnumpos=0
medianum=0
while quantnum < 10:
    num = int(input('digite um número: '))
    quantnum += 1
    if num < 0:
      print(f"o número {num} é negativo")
    else:
      somanum += num
      quantnumpos +=1

medianum = somanum/quantnumpos
print(f"A média dos números positivos é {medianum}.")

"""2)"""

num = 0
quantnum = 0
while quantnum < 10:
  quantnum += 1
  num = int(input("digite um número: "))
  if num % 2 == 0:
    print(f'o número {num} é par')
  else:
    print(f'o número {num} é impar')

"""3)"""

def encontrar_menor_e_maior():
    menor = float('inf')  # Começa com o maior valor possível
    maior = float('-inf')  # Começa com o menor valor possível

    while True:
        numero = int(input("Digite um número (0 para terminar): "))
        if numero == 0:
            break
        if numero > maior:
            maior = numero
        if numero < menor:
            menor = numero

    print(f"O menor número é: {menor}")
    print(f"O maior número é: {maior}")

encontrar_menor_e_maior()

"""4)"""

def soma_pares_impares():
    soma_pares = 0
    soma_impares = 0

    for numero in range(1, 101):
        if numero % 2 == 0:
            soma_pares += numero
        else:
            soma_impares += numero

    print(f"A soma dos números pares entre 1 e 100 é: {soma_pares}")
    print(f"A soma dos números ímpares entre 1 e 100 é: {soma_impares}")